### ISSUE TITLE
Remove non-affected files from search

### ISSUE THREAD

**Issue by tphillip33** [Qualys/log4jscanwin#16]
This problem only affects "log4j-core*".  This should only report on "log4j-core*" files.

**Comment by romw** [comment]
While that is true in the context of CVE-2021-44228 or CVE-2021-45046, it doesn't really apply to CVE-2021-4104.

We have opted to report anything we find that contains traces of Log4j to the platform to aide companies in tracking their mitigation efforts through various offerings.  In order to do that we needed to report on everything and make the determinations within the platform itself.
